language: node_js
node_js:
  - node
script:
- npm install
- npm install -g serve > /dev/null
- serve -p 3000 > /dev/null &
- sleep 1
- ./node_modules/phantomjs-prebuilt/bin/phantomjs test/phantom-runner.js
