name: "Android Bridge Tests"
on: push
jobs:
    test:
        timeout-minutes: 15
        runs-on: macos-11
        steps:
            - name: "Checkout internal"
              uses: actions/checkout@v2

            - name: "Clone Android Repo"
              uses: actions/checkout@v2
              with:
                repository: mParticle/mparticle-android-sdk
                ref: development
                path: mparticle-android-sdk
            - name: "Install JDK 11"
              uses: actions/setup-java@v2
              with:
                distribution: "zulu"
                java-version: "11"    
            - name: "Build Files"
              run: |
                npm ci
                npm run build:iife
            - name: "Run Instrumented Tests"
              uses: reactivecircus/android-emulator-runner@v2.20.0
              with:
                working-directory: mparticle-android-sdk
                api-level: 29
                script: ./gradlew :android-core:cAT -Pandroid.testInstrumentationRunnerArguments.class=com.mparticle.internal.MParticleJSInterfaceITest -Pjs-sdk-file=../dist/mparticle.js
            - name: "Archive Test Results"
              if: ${{ always() }}
              uses: actions/upload-artifact@v2
              with:
                  name: test-results
                  path: mparticle-android-sdk/android-core/build/reports/androidTests/connected/**